<a href="https://colab.research.google.com/github/Midd98/tareas/blob/master/7.-problema_mochila.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # Problema de la Mochila
 
 El problema de la mochila surge en areas de investigacion de operaciones en las cuales se requiere alojar un numero de items con el maximo valor bajo ciertas restricciones. Si hacemos $X=\{x_1,\ldots,x_n\}$ un conjunto de items, con $x_i \in \{0,1\}$ siendo una variable binaria que indica la presencia del item $i$, $W=\{w_1,\ldots,w_n\}$ los pesos de los items y $V=\{v_1,\ldots,v_n\}$ el valor asociado a cada uno de los items, el problema de optimizacion puede ser escrito como:
 
 $F(X)=\operatorname{max}\sum_i x_i*v_i$
  
  Dado 
  
 $\sum_i x_i*w_i < W_{max}$
  

In [0]:
from itertools import chain, combinations

def powerset(iterable):
    "powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"
    s = list(iterable)
    return chain.from_iterable(combinations(s, r) for r in range(len(s)+1))

In [2]:
import random
import numpy as np

n=5
W = [random.randint(20, 1000) for _ in range(n)]  # peso
V  = [random.randint(10, 800) for _ in range(n)] # valor
W_max=1000
print('pesos : ',W)
print('valores : ',V)
print('------------------------------')
for i,p in enumerate(powerset(range(n))):
    print('Mochila {0}, items : {1}, valor : {2}, peso : {3}'.format(
            i,p,np.sum([V[i] for i in p]),np.sum([W[i] for i in p])))

pesos :  [237, 408, 549, 814, 676]
valores :  [124, 738, 114, 489, 446]
------------------------------
Mochila 0, items : (), valor : 0.0, peso : 0.0
Mochila 1, items : (0,), valor : 124, peso : 237
Mochila 2, items : (1,), valor : 738, peso : 408
Mochila 3, items : (2,), valor : 114, peso : 549
Mochila 4, items : (3,), valor : 489, peso : 814
Mochila 5, items : (4,), valor : 446, peso : 676
Mochila 6, items : (0, 1), valor : 862, peso : 645
Mochila 7, items : (0, 2), valor : 238, peso : 786
Mochila 8, items : (0, 3), valor : 613, peso : 1051
Mochila 9, items : (0, 4), valor : 570, peso : 913
Mochila 10, items : (1, 2), valor : 852, peso : 957
Mochila 11, items : (1, 3), valor : 1227, peso : 1222
Mochila 12, items : (1, 4), valor : 1184, peso : 1084
Mochila 13, items : (2, 3), valor : 603, peso : 1363
Mochila 14, items : (2, 4), valor : 560, peso : 1225
Mochila 15, items : (3, 4), valor : 935, peso : 1490
Mochila 16, items : (0, 1, 2), valor : 976, peso : 1194
Mochila 17, items : (0, 1

In [0]:
# A Dynamic Programming based Python Program for 0-1 Knapsack problem 
# Returns the maximum value that can be put in a knapsack of capacity W 
def knapsack(W_max, W, V, n): 
    C = [[0 for x in range(W_max+1)] for x in range(n+1)] 
    # Build table in bottom up manner 
    for i in range(n+1): 
        for w in range(W_max+1): 
            if i==0 or w==0: 
                C[i][w] = 0
            elif W[i-1] <= w: 
                C[i][w] = max(V[i-1] + C[i-1][w-W[i-1]],  C[i-1][w]) 
            else: 
                C[i][w] = C[i-1][w] 
  
    return C 

In [0]:
def knapsack_greedy(W, wt, val, n):
    # elements in the knapsack (the order must be consequent)
    v_in_knapsack = []
    w_in_knapsack = []
    # current weight of all the elements put in the knapsack so far
    weight_in_knapsack = 0
    # sort elements by purity in descendant order
    for v_i,w_i in sorted(zip(val,wt),key=lambda x:x[0]/x[1] if x[1]!=0 else x[0], reverse=True):
        if w_i + weight_in_knapsack <= W:  # if I can carry it,
            v_in_knapsack.append(v_i)
            w_in_knapsack.append(w_i)
            weight_in_knapsack += w_i

    return v_in_knapsack, w_in_knapsack

In [5]:
# Example from Grokking Algorithms. p161
import numpy as np

values = [1500,3000,2000]
weights = [[1,4,3]]
capacities = [4]

C=knapsack(capacities[0],weights[0],values,len(values))

print(np.asarray(C))

[[   0    0    0    0    0]
 [   0 1500 1500 1500 1500]
 [   0 1500 1500 1500 3000]
 [   0 1500 1500 2000 3500]]


In [6]:
v_c,w_c=knapsack_greedy(capacities[0],weights[0],values,len(values))

print(v_c)
print(w_c)

[1500, 2000]
[1, 3]


In [0]:
# Example from https://developers.google.com/optimization/bin/knapsack

values = [
    360, 83, 59, 130, 431, 67, 230, 52, 93, 125, 670, 892, 600, 38, 48, 147,
    78, 256, 63, 17, 120, 164, 432, 35, 92, 110, 22, 42, 50, 323, 514, 28,
    87, 73, 78, 15, 26, 78, 210, 36, 85, 189, 274, 43, 33, 10, 19, 389, 276,
    312
]
weights = [[
    7, 0, 30, 22, 80, 94, 11, 81, 70, 64, 59, 18, 0, 36, 3, 8, 15, 42, 9, 0,
    42, 47, 52, 32, 26, 48, 55, 6, 29, 84, 2, 4, 18, 56, 7, 29, 93, 44, 71,
    3, 86, 66, 31, 65, 0, 79, 20, 65, 52, 13
]]
capacities = [850]

#C=knapsack(capacities[0],weights[0],values,len(values))
#print('Total value = {0}'.format(C[-1][-1]))
#print('Total weight = {0}'.format(len(C[0])-1))

In [8]:
import numpy as np

v_c,w_c=knapsack_greedy(capacities[0],weights[0],values,len(values))

print('Total value = ',np.sum(v_c))
print('Total weight = ',np.sum(w_c))

Total value =  7534
Total weight =  850


Solución Tarea 2, punto 1.2(3 en la guía)

In [0]:
import time
import pandas
import IPython

In [0]:
def obtener_tiempo(method, capacidad, pesos, values, n):
  if( method=='knapsack' ):
    t = time.clock()
    C = knapsack(capacidad,pesos, values, n)
    t = time.clock() - t
  elif (method == 'knapsack_greedy'):
    t = time.clock()
    C = knapsack_greedy(capacidad,pesos, values, n)
    t = time.clock() - t
  else:
    raise Exception('Metodo no soportado!')
  return t

In [0]:
class Tarea:
  def __init__(self):
    # tiempos = { 'n' : { 'w':{'metodo1':t1 , 'metodo2':t2} } }
    self._tiempos = { 100 : {}, 1000:{}, 5000:{} }
  def obtener_tiempo_method(self, method, capacidad, pesos, values, n):
    #Validaciones
    if n not in self._tiempos.keys():
      raise Exception('Dimension N no permitida')
    if method not in ["knapsack", "knapsack_greedy"]:
      raise Exception('Metodo no soportado!')
    #Nuevos casos
    if( capacidad not in self._tiempos[n].keys() ):
      self._tiempos[n][capacidad] = {}

    if( method in self._tiempos[n][capacidad].keys() ):#Tiempo ya fue calculado para estas dimensiones (n, w)
      return

    if( method=='knapsack' ):
      t = time.clock()
      C = knapsack(capacidad,pesos, values, n)
      t = time.clock() - t
    elif (method == 'knapsack_greedy'):
      t = time.clock()
      C = knapsack_greedy(capacidad,pesos, values, n)
      t = time.clock() - t
    self._tiempos[n][capacidad][method] = t
  def obtener_tiempos_peso(self, n, W_max):
    W = [random.randint(20, W_max) for _ in range(n)]  # peso
    V  = [random.randint(10, 800) for _ in range(n)] # valor
    self.obtener_tiempo_method('knapsack',W_max,W,V,len(V))
    self.obtener_tiempo_method('knapsack_greedy',W_max,W,V,len(V))
  def getTiempos(self):
    return self._tiempos
  

In [0]:
tar = Tarea()

In [0]:
#tar.obtener_tiempos_peso(n, w)
N = [100, 1000, 5000]
W = [100,1000, 5000,50000]
for n in N:
  for w in W:
    tar.obtener_tiempos_peso(n, w)

In [19]:
tiempos = tar.getTiempos()
for n, W in tiempos.items():
  print("\n\nN:"+str(n))
  table_data = {}
  for w, data in W.items():
    table_data.update({"W_Max:"+str(w): [data['knapsack'],data['knapsack_greedy']] })
  table_frame = pandas.DataFrame(table_data, index = ["knapsack","knapsack_greedy"])
  IPython.display.display(table_frame)




N:100


W_Max:100  W_Max:1000  W_Max:5000  W_Max:10000  W_Max:50000
knapsack          0.005778    0.034739    0.181776     0.388696     1.780958
knapsack_greedy   0.000100    0.000078    0.000087     0.000109     0.000109



N:1000


W_Max:100  W_Max:1000  W_Max:5000  W_Max:10000  W_Max:50000
knapsack          0.035079    0.389766    1.999228     3.883506    19.496846
knapsack_greedy   0.000573    0.000580    0.000822     0.000645     0.000614



N:5000


W_Max:100  W_Max:1000  W_Max:5000  W_Max:10000  W_Max:50000
knapsack          0.178674    1.971682   10.126758    20.488218   102.409223
knapsack_greedy   0.002905    0.003203    0.003199     0.003281     0.003801